[[language]]
name = "typescript"
auto-format = true
formatter = { command = "just", args = ["fmt-helix"] }

[[language]]
name = "javascript"
auto-format = true
formatter = { command = "just", args = ["fmt-helix"] }

