/* Automatically @generated by tree-sitter v0.25.4 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 45
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 23
#define ALIAS_COUNT 0
#define TOKEN_COUNT 13
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_fn = 1,
  anon_sym_LPAREN = 2,
  anon_sym_RPAREN = 3,
  anon_sym_LBRACE = 4,
  anon_sym_RBRACE = 5,
  sym_identifier = 6,
  anon_sym_return = 7,
  anon_sym_EQ = 8,
  anon_sym_DQUOTE = 9,
  sym__normal_string_content = 10,
  sym_escape_sequence = 11,
  sym_number = 12,
  sym_kcl_program = 13,
  sym_body_item = 14,
  sym_variable_declaration = 15,
  sym_fn_definition = 16,
  sym__expr = 17,
  sym_return_stmt = 18,
  sym_non_fn_definition = 19,
  sym_string = 20,
  aux_sym__string_content = 21,
  aux_sym_kcl_program_repeat1 = 22,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_fn] = "fn",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_identifier] = "identifier",
  [anon_sym_return] = "return",
  [anon_sym_EQ] = "=",
  [anon_sym_DQUOTE] = "\"",
  [sym__normal_string_content] = "_normal_string_content",
  [sym_escape_sequence] = "escape_sequence",
  [sym_number] = "number",
  [sym_kcl_program] = "kcl_program",
  [sym_body_item] = "body_item",
  [sym_variable_declaration] = "variable_declaration",
  [sym_fn_definition] = "fn_definition",
  [sym__expr] = "_expr",
  [sym_return_stmt] = "return_stmt",
  [sym_non_fn_definition] = "non_fn_definition",
  [sym_string] = "string",
  [aux_sym__string_content] = "_string_content",
  [aux_sym_kcl_program_repeat1] = "kcl_program_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_identifier] = sym_identifier,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym__normal_string_content] = sym__normal_string_content,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_number] = sym_number,
  [sym_kcl_program] = sym_kcl_program,
  [sym_body_item] = sym_body_item,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_fn_definition] = sym_fn_definition,
  [sym__expr] = sym__expr,
  [sym_return_stmt] = sym_return_stmt,
  [sym_non_fn_definition] = sym_non_fn_definition,
  [sym_string] = sym_string,
  [aux_sym__string_content] = aux_sym__string_content,
  [aux_sym_kcl_program_repeat1] = aux_sym_kcl_program_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym__normal_string_content] = {
    .visible = false,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_kcl_program] = {
    .visible = true,
    .named = true,
  },
  [sym_body_item] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_fn_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [sym_return_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_non_fn_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__string_content] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_kcl_program_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 2,
  [7] = 3,
  [8] = 5,
  [9] = 9,
  [10] = 10,
  [11] = 10,
  [12] = 9,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 21,
  [25] = 18,
  [26] = 15,
  [27] = 16,
  [28] = 19,
  [29] = 22,
  [30] = 23,
  [31] = 13,
  [32] = 17,
  [33] = 14,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 36,
  [41] = 35,
  [42] = 37,
  [43] = 39,
  [44] = 38,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      ADVANCE_MAP(
        '"', 24,
        '(', 11,
        ')', 12,
        '-', 5,
        '0', 28,
        '=', 23,
        '\\', 6,
        'f', 16,
        'r', 15,
        '{', 13,
        '}', 14,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(3);
      if (lookahead == '"') ADVANCE(24);
      if (lookahead == '\\') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(24);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == '0') ADVANCE(28);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(24);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 5:
      if (lookahead == '0') ADVANCE(28);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 6:
      ADVANCE_MAP(
        '"', 27,
        '/', 27,
        '\\', 27,
        'b', 27,
        'f', 27,
        'n', 27,
        'r', 27,
        't', 27,
        'u', 27,
      );
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      ADVANCE_MAP(
        '"', 24,
        '(', 11,
        ')', 12,
        '-', 5,
        '0', 28,
        '=', 23,
        'f', 16,
        'r', 15,
        '{', 13,
        '}', 14,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_fn);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_return);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym__normal_string_content);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym__normal_string_content);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(30);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(4);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(30);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_kcl_program] = STATE(34),
    [sym_body_item] = STATE(4),
    [sym_variable_declaration] = STATE(25),
    [sym_fn_definition] = STATE(31),
    [sym_return_stmt] = STATE(25),
    [sym_non_fn_definition] = STATE(31),
    [aux_sym_kcl_program_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_fn] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_return] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 1,
      anon_sym_fn,
    ACTIONS(16), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_return,
    STATE(2), 2,
      sym_body_item,
      aux_sym_kcl_program_repeat1,
    STATE(25), 2,
      sym_variable_declaration,
      sym_return_stmt,
    STATE(31), 2,
      sym_fn_definition,
      sym_non_fn_definition,
  [25] = 7,
    ACTIONS(22), 1,
      anon_sym_fn,
    ACTIONS(24), 1,
      anon_sym_RBRACE,
    ACTIONS(26), 1,
      sym_identifier,
    ACTIONS(28), 1,
      anon_sym_return,
    STATE(5), 2,
      sym_body_item,
      aux_sym_kcl_program_repeat1,
    STATE(13), 2,
      sym_fn_definition,
      sym_non_fn_definition,
    STATE(18), 2,
      sym_variable_declaration,
      sym_return_stmt,
  [50] = 7,
    ACTIONS(5), 1,
      anon_sym_fn,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_return,
    ACTIONS(30), 1,
      ts_builtin_sym_end,
    STATE(2), 2,
      sym_body_item,
      aux_sym_kcl_program_repeat1,
    STATE(25), 2,
      sym_variable_declaration,
      sym_return_stmt,
    STATE(31), 2,
      sym_fn_definition,
      sym_non_fn_definition,
  [75] = 7,
    ACTIONS(22), 1,
      anon_sym_fn,
    ACTIONS(26), 1,
      sym_identifier,
    ACTIONS(28), 1,
      anon_sym_return,
    ACTIONS(32), 1,
      anon_sym_RBRACE,
    STATE(6), 2,
      sym_body_item,
      aux_sym_kcl_program_repeat1,
    STATE(13), 2,
      sym_fn_definition,
      sym_non_fn_definition,
    STATE(18), 2,
      sym_variable_declaration,
      sym_return_stmt,
  [100] = 7,
    ACTIONS(11), 1,
      anon_sym_RBRACE,
    ACTIONS(34), 1,
      anon_sym_fn,
    ACTIONS(37), 1,
      sym_identifier,
    ACTIONS(40), 1,
      anon_sym_return,
    STATE(6), 2,
      sym_body_item,
      aux_sym_kcl_program_repeat1,
    STATE(13), 2,
      sym_fn_definition,
      sym_non_fn_definition,
    STATE(18), 2,
      sym_variable_declaration,
      sym_return_stmt,
  [125] = 7,
    ACTIONS(22), 1,
      anon_sym_fn,
    ACTIONS(26), 1,
      sym_identifier,
    ACTIONS(28), 1,
      anon_sym_return,
    ACTIONS(43), 1,
      anon_sym_RBRACE,
    STATE(8), 2,
      sym_body_item,
      aux_sym_kcl_program_repeat1,
    STATE(13), 2,
      sym_fn_definition,
      sym_non_fn_definition,
    STATE(18), 2,
      sym_variable_declaration,
      sym_return_stmt,
  [150] = 7,
    ACTIONS(22), 1,
      anon_sym_fn,
    ACTIONS(26), 1,
      sym_identifier,
    ACTIONS(28), 1,
      anon_sym_return,
    ACTIONS(45), 1,
      anon_sym_RBRACE,
    STATE(6), 2,
      sym_body_item,
      aux_sym_kcl_program_repeat1,
    STATE(13), 2,
      sym_fn_definition,
      sym_non_fn_definition,
    STATE(18), 2,
      sym_variable_declaration,
      sym_return_stmt,
  [175] = 3,
    ACTIONS(49), 1,
      anon_sym_DQUOTE,
    ACTIONS(47), 2,
      sym_identifier,
      sym_number,
    STATE(26), 2,
      sym__expr,
      sym_string,
  [187] = 3,
    ACTIONS(49), 1,
      anon_sym_DQUOTE,
    ACTIONS(51), 2,
      sym_identifier,
      sym_number,
    STATE(24), 2,
      sym__expr,
      sym_string,
  [199] = 3,
    ACTIONS(55), 1,
      anon_sym_DQUOTE,
    ACTIONS(53), 2,
      sym_identifier,
      sym_number,
    STATE(21), 2,
      sym__expr,
      sym_string,
  [211] = 3,
    ACTIONS(55), 1,
      anon_sym_DQUOTE,
    ACTIONS(57), 2,
      sym_identifier,
      sym_number,
    STATE(15), 2,
      sym__expr,
      sym_string,
  [223] = 2,
    ACTIONS(61), 1,
      anon_sym_RBRACE,
    ACTIONS(59), 3,
      anon_sym_fn,
      sym_identifier,
      anon_sym_return,
  [232] = 3,
    ACTIONS(63), 1,
      anon_sym_DQUOTE,
    STATE(17), 1,
      aux_sym__string_content,
    ACTIONS(65), 2,
      sym__normal_string_content,
      sym_escape_sequence,
  [243] = 2,
    ACTIONS(67), 1,
      ts_builtin_sym_end,
    ACTIONS(69), 3,
      anon_sym_fn,
      sym_identifier,
      anon_sym_return,
  [252] = 2,
    ACTIONS(71), 1,
      ts_builtin_sym_end,
    ACTIONS(73), 3,
      anon_sym_fn,
      sym_identifier,
      anon_sym_return,
  [261] = 3,
    ACTIONS(75), 1,
      anon_sym_DQUOTE,
    STATE(20), 1,
      aux_sym__string_content,
    ACTIONS(77), 2,
      sym__normal_string_content,
      sym_escape_sequence,
  [272] = 2,
    ACTIONS(81), 1,
      anon_sym_RBRACE,
    ACTIONS(79), 3,
      anon_sym_fn,
      sym_identifier,
      anon_sym_return,
  [281] = 2,
    ACTIONS(83), 1,
      ts_builtin_sym_end,
    ACTIONS(85), 3,
      anon_sym_fn,
      sym_identifier,
      anon_sym_return,
  [290] = 3,
    ACTIONS(87), 1,
      anon_sym_DQUOTE,
    STATE(20), 1,
      aux_sym__string_content,
    ACTIONS(89), 2,
      sym__normal_string_content,
      sym_escape_sequence,
  [301] = 2,
    ACTIONS(92), 1,
      ts_builtin_sym_end,
    ACTIONS(94), 3,
      anon_sym_fn,
      sym_identifier,
      anon_sym_return,
  [310] = 2,
    ACTIONS(96), 1,
      ts_builtin_sym_end,
    ACTIONS(98), 3,
      anon_sym_fn,
      sym_identifier,
      anon_sym_return,
  [319] = 2,
    ACTIONS(100), 1,
      ts_builtin_sym_end,
    ACTIONS(102), 3,
      anon_sym_fn,
      sym_identifier,
      anon_sym_return,
  [328] = 2,
    ACTIONS(92), 1,
      anon_sym_RBRACE,
    ACTIONS(94), 3,
      anon_sym_fn,
      sym_identifier,
      anon_sym_return,
  [337] = 2,
    ACTIONS(81), 1,
      ts_builtin_sym_end,
    ACTIONS(79), 3,
      anon_sym_fn,
      sym_identifier,
      anon_sym_return,
  [346] = 2,
    ACTIONS(67), 1,
      anon_sym_RBRACE,
    ACTIONS(69), 3,
      anon_sym_fn,
      sym_identifier,
      anon_sym_return,
  [355] = 2,
    ACTIONS(71), 1,
      anon_sym_RBRACE,
    ACTIONS(73), 3,
      anon_sym_fn,
      sym_identifier,
      anon_sym_return,
  [364] = 2,
    ACTIONS(83), 1,
      anon_sym_RBRACE,
    ACTIONS(85), 3,
      anon_sym_fn,
      sym_identifier,
      anon_sym_return,
  [373] = 2,
    ACTIONS(96), 1,
      anon_sym_RBRACE,
    ACTIONS(98), 3,
      anon_sym_fn,
      sym_identifier,
      anon_sym_return,
  [382] = 2,
    ACTIONS(100), 1,
      anon_sym_RBRACE,
    ACTIONS(102), 3,
      anon_sym_fn,
      sym_identifier,
      anon_sym_return,
  [391] = 2,
    ACTIONS(61), 1,
      ts_builtin_sym_end,
    ACTIONS(59), 3,
      anon_sym_fn,
      sym_identifier,
      anon_sym_return,
  [400] = 3,
    ACTIONS(104), 1,
      anon_sym_DQUOTE,
    STATE(20), 1,
      aux_sym__string_content,
    ACTIONS(77), 2,
      sym__normal_string_content,
      sym_escape_sequence,
  [411] = 3,
    ACTIONS(106), 1,
      anon_sym_DQUOTE,
    STATE(32), 1,
      aux_sym__string_content,
    ACTIONS(108), 2,
      sym__normal_string_content,
      sym_escape_sequence,
  [422] = 1,
    ACTIONS(110), 1,
      ts_builtin_sym_end,
  [426] = 1,
    ACTIONS(112), 1,
      anon_sym_LBRACE,
  [430] = 1,
    ACTIONS(114), 1,
      anon_sym_EQ,
  [434] = 1,
    ACTIONS(116), 1,
      anon_sym_RPAREN,
  [438] = 1,
    ACTIONS(118), 1,
      sym_identifier,
  [442] = 1,
    ACTIONS(120), 1,
      anon_sym_LPAREN,
  [446] = 1,
    ACTIONS(122), 1,
      anon_sym_EQ,
  [450] = 1,
    ACTIONS(124), 1,
      anon_sym_LBRACE,
  [454] = 1,
    ACTIONS(126), 1,
      anon_sym_RPAREN,
  [458] = 1,
    ACTIONS(128), 1,
      anon_sym_LPAREN,
  [462] = 1,
    ACTIONS(130), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 25,
  [SMALL_STATE(4)] = 50,
  [SMALL_STATE(5)] = 75,
  [SMALL_STATE(6)] = 100,
  [SMALL_STATE(7)] = 125,
  [SMALL_STATE(8)] = 150,
  [SMALL_STATE(9)] = 175,
  [SMALL_STATE(10)] = 187,
  [SMALL_STATE(11)] = 199,
  [SMALL_STATE(12)] = 211,
  [SMALL_STATE(13)] = 223,
  [SMALL_STATE(14)] = 232,
  [SMALL_STATE(15)] = 243,
  [SMALL_STATE(16)] = 252,
  [SMALL_STATE(17)] = 261,
  [SMALL_STATE(18)] = 272,
  [SMALL_STATE(19)] = 281,
  [SMALL_STATE(20)] = 290,
  [SMALL_STATE(21)] = 301,
  [SMALL_STATE(22)] = 310,
  [SMALL_STATE(23)] = 319,
  [SMALL_STATE(24)] = 328,
  [SMALL_STATE(25)] = 337,
  [SMALL_STATE(26)] = 346,
  [SMALL_STATE(27)] = 355,
  [SMALL_STATE(28)] = 364,
  [SMALL_STATE(29)] = 373,
  [SMALL_STATE(30)] = 382,
  [SMALL_STATE(31)] = 391,
  [SMALL_STATE(32)] = 400,
  [SMALL_STATE(33)] = 411,
  [SMALL_STATE(34)] = 422,
  [SMALL_STATE(35)] = 426,
  [SMALL_STATE(36)] = 430,
  [SMALL_STATE(37)] = 434,
  [SMALL_STATE(38)] = 438,
  [SMALL_STATE(39)] = 442,
  [SMALL_STATE(40)] = 446,
  [SMALL_STATE(41)] = 450,
  [SMALL_STATE(42)] = 454,
  [SMALL_STATE(43)] = 458,
  [SMALL_STATE(44)] = 462,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_kcl_program, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_kcl_program_repeat1, 2, 0, 0),
  [13] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_kcl_program_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [16] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_kcl_program_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [19] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_kcl_program_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [22] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [24] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [26] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [28] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_kcl_program, 1, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_kcl_program_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_kcl_program_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_kcl_program_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_non_fn_definition, 3, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_non_fn_definition, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body_item, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body_item, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__string_content, 2, 0, 0),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__string_content, 2, 0, 0), SHIFT_REPEAT(20),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_stmt, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_stmt, 2, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn_definition, 6, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fn_definition, 6, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn_definition, 7, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fn_definition, 7, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [110] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_kcl(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
