name: CI

on:
  pull_request:
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp
      - ".github/workflows/ci.yml"

jobs:
  test:
    name: Test parser
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v1
      - uses: taiki-e/install-action@just
      - name: Run tests
        run: just test
